src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Texte = null;

    #[ORM\ManyToOne(inversedBy: 'Commentaires')]
    private ?Recette $recette = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $Auteur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTexte(): ?string
    {
        return $this->Texte;
    }

    public function setTexte(string $Texte): static
    {
        $this->Texte = $Texte;

        return $this;
    }

    public function getRecette(): ?Recette
    {
        return $this->recette;
    }

    public function setRecette(?Recette $recette): static
    {
        $this->recette = $recette;

        return $this;
    }

    public function getAuteur(): ?Utilisateur
    {
        return $this->Auteur;
    }

    public function setAuteur(?Utilisateur $Auteur): static
    {
        $this->Auteur = $Auteur;

        return $this;
    }
}

src/Entity/Ratings.php
<?php

namespace App\Entity;

use App\Repository\RatingsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: RatingsRepository::class)]
class Ratings
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $Value = null;

    #[ORM\ManyToOne(inversedBy: 'ratings')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Unique]
    private ?Recette $Recette = null;

    #[ORM\ManyToOne(inversedBy: 'ratings')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Unique]
    private ?Utilisateur $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getValue(): ?int
    {
        return $this->Value;
    }

    public function setValue(int $Value): static
    {
        $this->Value = $Value;

        return $this;
    }

    public function getRecette(): ?Recette
    {
        return $this->Recette;
    }

    public function setRecette(?Recette $Recette): static
    {
        $this->Recette = $Recette;

        return $this;
    }

    public function getUser(): ?Utilisateur
    {
        return $this->User;
    }

    public function setUser(?Utilisateur $User): static
    {
        $this->User = $User;

        return $this;
    }
}

src/Entity/Recette.php
<?php

namespace App\Entity;

use App\Repository\RecetteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: RecetteRepository::class)]
class Recette
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $TempsPreparation = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $TempsCuisson = null;

    #[ORM\Column]
    private ?int $Portions = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Instructions = null;

    #[ORM\Column(nullable: true)]
    private ?float $Note = null;

    #[ORM\ManyToOne(inversedBy: 'recettes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $Categorie = null;

    #[ORM\ManyToOne(inversedBy: 'recettes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $Auteur = null;

    /**
     * @var Collection<int, Commentaire>
     */
    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'recette',orphanRemoval: true, cascade: ["remove"])]
    private Collection $Commentaires;

    /**
     * @var Collection<int, RecetteIngredient>
     */
    #[ORM\OneToMany(targetEntity: RecetteIngredient::class, mappedBy: 'recette', orphanRemoval: true, cascade: ["remove"])]
    private Collection $ingredients;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCreated = null;

    /**
     * @var Collection<int, Ratings>
     */
    #[ORM\OneToMany(targetEntity: Ratings::class, mappedBy: 'Recette')]
    private Collection $ratings;

    public function __construct()
    {
        $this->Commentaires = new ArrayCollection();
        $this->ingredients = new ArrayCollection();
        $this->ratings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getTempsPreparation(): ?\DateTimeInterface
    {
        return $this->TempsPreparation;
    }

    public function setTempsPreparation(\DateTimeInterface $TempsPreparation): static
    {
        $this->TempsPreparation = $TempsPreparation;

        return $this;
    }

    public function getTempsCuisson(): ?\DateTimeInterface
    {
        return $this->TempsCuisson;
    }

    public function setTempsCuisson(\DateTimeInterface $TempsCuisson): static
    {
        $this->TempsCuisson = $TempsCuisson;

        return $this;
    }

    public function getPortions(): ?int
    {
        return $this->Portions;
    }

    public function setPortions(int $Portions): static
    {
        $this->Portions = $Portions;

        return $this;
    }

    public function getInstructions(): ?string
    {
        return $this->Instructions;
    }

    public function setInstructions(string $Instructions): static
    {
        $this->Instructions = $Instructions;

        return $this;
    }

    public function getNote(): ?float
    {
        return $this->Note;
    }

    public function setNote(float $Note): static
    {
        $this->Note = $Note;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categorie $Categorie): static
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function getAuteur(): ?Utilisateur
    {
        return $this->Auteur;
    }

    public function setAuteur(?Utilisateur $Auteur): static
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->Commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->Commentaires->contains($commentaire)) {
            $this->Commentaires->add($commentaire);
            $commentaire->setRecette($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->Commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getRecette() === $this) {
                $commentaire->setRecette(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, RecetteIngredient>
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(RecetteIngredient $ingredient): static
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients->add($ingredient);
            $ingredient->setRecette($this);
        }

        return $this;
    }

    public function removeIngredient(RecetteIngredient $ingredient): static
    {
        if ($this->ingredients->removeElement($ingredient)) {
            // set the owning side to null (unless already changed)
            if ($ingredient->getRecette() === $this) {
                $ingredient->setRecette(null);
            }
        }

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->dateCreated;
    }

    public function setDateCreated(\DateTimeInterface $dateCreated): static
    {
        $this->dateCreated = $dateCreated;

        return $this;
    }

    /**
     * @return Collection<int, Ratings>
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Ratings $rating): static
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings->add($rating);
            $rating->setRecette($this);
        }

        return $this;
    }

    public function removeRating(Ratings $rating): static
    {
        if ($this->ratings->removeElement($rating)) {
            // set the owning side to null (unless already changed)
            if ($rating->getRecette() === $this) {
                $rating->setRecette(null);
            }
        }

        return $this;
    }

    public function updateNote(): static
    {
        $totalRatings = count($this->ratings);
        if ($totalRatings > 0){
            $sumRatings = array_reduce($this->ratings->toArray(), function ($sum, $rating){
                return $sum + $rating->getValue();
            }, 0);
            $this->Note = $sumRatings/$totalRatings;
        } else{
            $this->Note = null;
        }
        return $this;
    }
}

src/Entity/RecetteIngredient.php
<?php

namespace App\Entity;

use App\Repository\RecetteIngredientRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RecetteIngredientRepository::class)]
class RecetteIngredient
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $Quantite = null;

    #[ORM\ManyToOne(inversedBy: 'ingredients')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Recette $recette = null;

    #[ORM\ManyToOne(inversedBy: 'recetteIngredients')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ingredient $Ingredient = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->Quantite;
    }

    public function setQuantite(int $Quantite): static
    {
        $this->Quantite = $Quantite;

        return $this;
    }

    public function getRecette(): ?Recette
    {
        return $this->recette;
    }

    public function setRecette(?Recette $recette): static
    {
        $this->recette = $recette;

        return $this;
    }

    public function getIngredient(): ?Ingredient
    {
        return $this->Ingredient;
    }

    public function setIngredient(?Ingredient $Ingredient): static
    {
        $this->Ingredient = $Ingredient;

        return $this;
    }
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Pseudo = null;

    /**
     * @var Collection<int, Recette>
     */
    #[ORM\OneToMany(targetEntity: Recette::class, mappedBy: 'Auteur', orphanRemoval: true, cascade: ["remove"])]
    private Collection $recettes;

    /**
     * @var Collection<int, Commentaire>
     */
    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'Auteur', orphanRemoval: true, cascade: ["remove"])]
    private Collection $commentaires;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $PhotoProfil = null;

    /**
     * @var Collection<int, Ratings>
     */
    #[ORM\OneToMany(targetEntity: Ratings::class, mappedBy: 'User')]
    private Collection $ratings;

    public function __construct()
    {
        $this -> recettes = new ArrayCollection();
        $this -> commentaires = new ArrayCollection();
        $this->ratings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this -> id;
    }

    public function getEmail(): ?string
    {
        return $this -> email;
    }

    public function setEmail(string $email): static
    {
        $this -> email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this -> email;
    }

    /**
     * @return list<string>
     * @see UserInterface
     *
     */
    public function getRoles(): array
    {
        $roles = $this -> roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique ( $roles );
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this -> roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this -> password;
    }

    public function setPassword(string $password): static
    {
        $this -> password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this -> Pseudo;
    }

    public function setPseudo(string $Pseudo): static
    {
        $this -> Pseudo = $Pseudo;

        return $this;
    }

    /**
     * @return Collection<int, Recette>
     */
    public function getRecettes(): Collection
    {
        return $this -> recettes;
    }

    public function addRecette(Recette $recette): static
    {
        if (!$this -> recettes -> contains ( $recette )) {
            $this -> recettes -> add ( $recette );
            $recette -> setAuteur ( $this );
        }

        return $this;
    }

    public function removeRecette(Recette $recette): static
    {
        if ($this -> recettes -> removeElement ( $recette )) {
            // set the owning side to null (unless already changed)
            if ($recette -> getAuteur () === $this) {
                $recette -> setAuteur ( null );
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this -> commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this -> commentaires -> contains ( $commentaire )) {
            $this -> commentaires -> add ( $commentaire );
            $commentaire -> setAuteur ( $this );
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this -> commentaires -> removeElement ( $commentaire )) {
            // set the owning side to null (unless already changed)
            if ($commentaire -> getAuteur () === $this) {
                $commentaire -> setAuteur ( null );
            }
        }

        return $this;
    }

    public function getPhotoProfil(): ?string
    {
        return $this->PhotoProfil;
    }

    public function setPhotoProfil(?string $PhotoProfil): static
    {
        $this->PhotoProfil = $PhotoProfil;

        return $this;
    }

    /**
     * @return Collection<int, Ratings>
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Ratings $rating): static
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings->add($rating);
            $rating->setUser($this);
        }

        return $this;
    }

    public function removeRating(Ratings $rating): static
    {
        if ($this->ratings->removeElement($rating)) {
            // set the owning side to null (unless already changed)
            if ($rating->getUser() === $this) {
                $rating->setUser(null);
            }
        }

        return $this;
    }
}

templates/recettes/ajoutIngredients.html.twig
{% extends 'base.html.twig' %}
{% block title %}Ajout Ingredients{% endblock %}

{% block body %}
    <h1>Ajoutez des ingredients</h1>
    {{ form_start(ingredientForm, {'attr': {'id': 'ingredient-form'}})  }}
    <div id="ingredient-container">
        <div class="ingredient-form form-container">
            <div class="form-row">
                {{ form_label(ingredientForm.Ingredient) }}
                {{ form_widget(ingredientForm.Ingredient, {'attr': {'class': 'input'}}) }}
            </div>
            <div class="form-row">
                {{ form_label(ingredientForm.Quantite) }}
                {{ form_widget(ingredientForm.Quantite, {'attr': {'class': 'input'}}) }}
                <button type="button" class="remove-ingredient form-button remove-button">Enlever</button>
            </div>
        </div>
    </div>
    <input type="hidden" name="ingredientsData" id="ingredients-data">
    <button type="button" id="add-ingredient" class="form-button"> ajouter un ingredient </button>
    <button type="submit" class="form-button"> Creer</button>
    {{ form_end(ingredientForm) }}

    <script src="{{ asset('js/modifyIngredient.js') }}"></script>
{% endblock %}

templates/recettes/desserts.html.twig
{% extends 'base.html.twig' %}
{% block title %}Desserts{% endblock %}

{% block body %}
    <h1>Desserts</h1>
    <section class="recettes-section">
        {% for recette in desserts %}
            <a class="recette-link" href="{{path('app_detail', {'id': recette.id}) }}">{{ recette.nom }}</a>
        {% endfor %}
    </section>
    <section class="navigation">
        {% if pageActuelle > 1 %}
            <a href="{{ path('app_desserts', {'page': pageActuelle - 1}) }}"> < </a>
        {% endif %}

        {% for page in 1..maxPages %}
            {% if page == pageActuelle %}
                <strong>{{ page }}</strong>
            {% else %}
                <a href="{{ path('app_desserts', {'page': page}) }}">{{ page }}</a>
            {% endif %}
        {% endfor %}

        {% if pageActuelle < maxPages %}
            <a href="{{ path('app_desserts', {'page': pageActuelle+1}) }}"> > </a>
        {% endif %}
    </section>
{% endblock %}

templates/recettes/detail.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ recette.nom }}{% endblock %}

{% block body %}
    <section class="detail-recette">
        <h1>{{ recette.nom }}</h1>
        <div>Auteur :
            {% if app.user == recette.Auteur %}
                    <a id="recette-auteur" href="{{ path('edit')}}"> {{ recette.Auteur.pseudo}}</a></div>
                {% else %}
                    <a id="recette-auteur" href="{{ path('otherProfile', {'pseudo': recette.Auteur.pseudo })}}"> {{ recette.Auteur.pseudo}}</a></div>
            {% endif %}

        <div>Note : {{ recette.note ? recette.note|number_format(2)  : 'Pas encore de Note'}}</div>
        <div>
            <h2>Ingredients</h2>
            <ul>
                {% for ingredient in recette.ingredients %}
                    <li>{{ ingredient.quantite}} {{ ingredient.Ingredient.Unite }} de {{ ingredient.Ingredient.nom }} </li>
                {% endfor %}
            </ul>
        </div>
        <div>Portions : {{ recette.portions }}</div>
        <div>Instructions : {{ recette.instructions }}</div>
        <div>Temps de preparation : {{ recette.tempsPreparation | date("H:i") }}</div>
        <div>Temps de cuisson : {{ recette.tempsCuisson | date("H:i") }}</div>
        <div><h2>Commentaires</h2>
            <ul>
                {% for commentaire in comments|slice(0,5) %}
                    <li>{{ commentaire.texte }}</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            {% if existingRating is null and app.user != recette.Auteur%}
                <h2>Notez cette recette</h2>
                {{ form_start(ratingForm) }}
                <section class="form-container">
                    <div class="form-row">
                        {{ form_label(ratingForm.Value) }}
                        {{ form_widget(ratingForm.Value,{'attr':{'class': 'input'}}) }}
                    </div>
                </section>
                <button class="form-button" type="submit">Notez</button>
                {{ form_end(ratingForm) }}
            {% endif %}
        </div>
        <div>
            {% if existingComment is null and app.user != recette.Auteur %}
                <h2>Ecrivez un commentaire</h2>
                {{ form_start(commentForm) }}
                <section class="form-container">
                    {{ form_widget(commentForm.Texte,{'attr':{'class': 'text-area-input'}}) }}
                </section>
                <button class="form-button" type="submit">Commentez</button>
                {{ form_end(commentForm) }}
            {% endif %}
        </div>
    </section>
    {% if app.user == recette.Auteur %}
        <div class="form-buttons">
            <button class="form-button"><a href="{{ path('app_modifRecette', {'id': recette.Id}) }}"> Modifiée votre recette</a></button>
        </div>
    {% endif %}
{% endblock %}

templates/recettes/entrees.html.twig
{% extends 'base.html.twig' %}
{% block title %}Entrees{% endblock %}

{% block body %}
    <h1>Entrees</h1>
    <section class="recettes-section">
        {% for recette in entrees %}
            <a class="recette-link" href="{{path('app_detail', {'id': recette.id}) }}">{{ recette.nom }}</a>
        {% endfor %}
    </section>

    <section class="navigation">
        {% if pageActuelle > 1 %}
            <a href="{{ path('app_entrees', {'page': pageActuelle - 1}) }}"> < </a>
        {% endif %}

        {% for page in 1..maxPages %}
            {% if page == pageActuelle %}
                <strong>{{ page }}</strong>
            {% else %}
                <a href="{{ path('app_entrees', {'page': page}) }}">{{ page }}</a>
            {% endif %}
        {% endfor %}

        {% if pageActuelle < maxPages %}
            <a href="{{ path('app_entrees', {'page': pageActuelle+1}) }}"> > </a>
        {% endif %}
    </section>
{% endblock %}

templates/recettes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
        <h1>Meilleures Recettes</h1>
    <section class="recettes-section">
        {% for recette in meilleuresRecettes %}
                <a class="recette-link" href="{{path('app_detail', {'id': recette.id}) }}">{{ recette.nom }}</a>
        {% endfor %}
    </section>
        <h2>Nouvelles Recettes</h2>
    <section class="recettes-section">
        {% for recette in nouvellesRecettes %}
                <a class="recette-link" href="{{path('app_detail', {'id': recette.id}) }}">{{ recette.nom }}</a>
        {% endfor %}
    </section>
{% endblock %}

templates/recettes/modifRecette.html.twig
{% extends 'base.html.twig' %}
{% block title %}Modifiée votre Recette{% endblock %}

{% block body %}
    <h1>Modifiée votre recette</h1>
    {{ form_start(modifForm) }}
    <div class="form-container">
        <div class="form-row">
            {{ form_label(modifForm.Nom) }}
            {{ form_widget(modifForm.Nom, {'attr': {'class': 'input'}}) }}
        </div>
        <div class="form-row">
            {{ form_label(modifForm.TempsPreparation) }}
            {{ form_widget(modifForm.TempsPreparation, {'attr': {'class': 'input'}}) }}
        </div>
        <div class="form-row">
            {{ form_label(modifForm.TempsCuisson) }}
            {{ form_widget(modifForm.TempsCuisson, {'attr': {'class': 'input'}}) }}
        </div>
        <div class="form-row">
            {{ form_label(modifForm.Portions) }}
            {{ form_widget(modifForm.Portions, {'attr': {'class': 'input'}}) }}
        </div>
        {{ form_errors(modifForm.Portions) }}
        <div class="text-row">
            {{ form_label(modifForm.Instructions) }}
            {{ form_widget(modifForm.Instructions, {'attr': {'class': 'text-area-input'}}) }}
        </div>
        <div class="form-row">
            {{ form_label(modifForm.Categorie) }}
            {{ form_widget(modifForm.Categorie, {'attr': {'class': 'input'}}) }}
        </div>
        <div class="form-buttons">
            {{ form_widget(modifForm.Enregistrer) }}
            {{ form_widget(modifForm.Supprimer) }}
        </div>
    </div>
    {{ form_end(modifForm) }}
    <div class="form-buttons">
        <button class="form-button"><a href="{{ path('app_modifIngredients', {'id': recette.id}) }}">Modifiér les ingredients</a></button>
    </div>
{% endblock %}

templates/recettes/plats.html.twig
{% extends 'base.html.twig' %}
{% block title %}Plats{% endblock %}

{% block body %}
    <h1>Plats</h1>
    <section class="recettes-section">
        {% for recette in plats %}
            <a class="recette-link" href="{{path('app_detail', {'id': recette.id}) }}">{{ recette.nom }}</a>
        {% endfor %}
    </section>
    <section class="navigation">
        {% if pageActuelle > 1 %}
            <a href="{{ path('app_plats', {'page': pageActuelle - 1}) }}"> < </a>
        {% endif %}

        {% for page in 1..maxPages %}
            {% if page == pageActuelle %}
                <strong>{{ page }}</strong>
            {% else %}
                <a href="{{ path('app_plats', {'page': page}) }}">{{ page }}</a>
            {% endif %}
        {% endfor %}

        {% if pageActuelle < maxPages %}
            <a href="{{ path('app_plats', {'page': pageActuelle+1}) }}"> > </a>
        {% endif %}
    </section>
{% endblock %}

templates/recettes/recherche.html.twig
{% extends 'base.html.twig' %}
{% block title %}Recherche{% endblock %}

{% block body %}
<h1>Decouvrez des recettes</h1>
    {{ form_start(searchForm) }}
    <div class="form-container">
        <div class="form-row">
            {{ form_label(searchForm.searchTerm) }}
            {{ form_widget(searchForm.searchTerm, {'attr': {'class': 'input'}}) }}
        </div>
        <div class="form-row">
            {{ form_label(searchForm.ingredientFilter) }}
            {{ form_widget(searchForm.ingredientFilter, {'attr': {'class': 'input'}}) }}
        </div>
        <button type="submit" class="form-button">Chercher</button>
    </div>
        {{ form_end(searchForm) }}

    {% if recettes is not empty %}

        <h2>Resultats</h2>
            <section class="recettes-section">
                {% for recette in recettes %}
                    <a class="recette-link" href="{{path('app_detail', {'id': recette.id}) }}">{{ recette.nom }}</a>
                {% endfor %}
            </section>
    {% endif %}
{% endblock %}